### ISSUE TITLE
JDCN ImageSAVE NODE. Please add overwrite toggle (w/o additional file naming at the end

### ISSUE THREAD

**Issue by Maelstrom2014** [daxcay/ComfyUI-JDCN#17]
Hello, Creator Daxcay! Plaese add this functionality:
JDCN ImageSAVE NODE. Please add overwrite toggle (w/o additional file naming at the end

**Comment by akr1999** [comment]
Hi, the node by default overwrites the file,  it is possible you are overwriting the file currently loaded in comfy try saving file in different directory.

I would suggest you to join discord server as your problem is workflow related.
Also please share pics there when asking for help of the problem you are currently facing.

https://discord.gg/z9rgJyfPWJ
