### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by davizca** [daxcay/ComfyUI-JDCN#4]
Im getting this message:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JDCN\__init__.py", line 41, in <module>
    from .LogicUtil.io_node import CLASS_MAPPINGS as IOMapping, CLASS_NAMES as IONames
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JDCN\LogicUtil\io_node.py", line 6, in <module>
    from .exif.exif import read_info_from_image_stealth
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JDCN\LogicUtil\exif\exif.py", line 3, in <module>
    import piexif
ModuleNotFoundError: No module named 'piexif'

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JDCN module for custom nodes: No module named 'piexif'

Any help here?

**Comment by daxcay** [comment]
I have updated the node please reinstall it by deleting ComfyUI-JDCN Folder and reinstall it using manager.

In case if the issue persists close everything,

Open CMD on comfyui path. 

For example:

```
D:\StabilityAI\Packages\ComfyUI 
```

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/2ff52b47-7043-48ac-8100-e677710a3fe1)

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/a8d1c739-f3b6-40f5-9b1f-bef683675920)


And then write this to activate the environment

```
.\venv\Scripts\activate
```

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/d9808ea2-c1b1-4e36-8dfe-f4279f6fb62c)

At last write this command: 

```
pip install piexif
````
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/b51e4378-da85-41b7-bf32-b77215899722)

Close after its done!

And start ComfyUI.

Do let me know if the issue was fixed by reinstalling node or using CMD method.

You can contact me on my discord server: https://discord.gg/GZVGqSHT

**Comment by davizca** [comment]
Thanks a lot. I'm not at home now but will try it and report results. Thanks for the quick response!

**Comment by davizca** [comment]
Hi again, you can close the issue since worked. What I did was just uninstall the old node, install via git clone the new one and update (try update) via ComfyUI Manager. Worked like a charm. Thanks for this!

**Comment by daxcay** [comment]
Solution:  **Delete ComfyUI-JDCN Folder and Re-install it using comfy ui manager.**
